screenblack/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
  title = StringField("Title", validators=[DataRequired()])
  content = TextAreaField("Content", validators=[DataRequired()])
  submit = SubmitField("Post")

screenblack/main/routes.py
from flask import request, render_template,Blueprint
from screenblack.models import Post

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
  page = request.args.get("page", default=1, type=int)
  posts = Post.query.order_by(Post.date_posted.desc()).paginate(page = page, per_page=5)
  return render_template("home.html", posts = posts)


@main.route("/about")
def about():
  return render_template("about.html", title="About")

screenblack/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from screenblack import db
from screenblack.models import Post
from screenblack.posts.forms import PostForm


posts = Blueprint("posts", __name__)



@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
  form = PostForm()
  if form.validate_on_submit():
    post = Post(title = form.title.data, content = form.content.data, author = current_user)
    db.session.add(post)
    db.session.commit()
    flash("Your post has been created.", "success")
    return redirect(url_for("main.home"))
  return render_template("create_update_post.html", title="New Post", form=form, legend="New Post")

@posts.route("/post/<int:post_id>")
def post(post_id):
  post = Post.query.get_or_404(post_id)
  return render_template("post.html", post=post, title=post.title)



@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
  post = Post.query.get_or_404(post_id)
  form = PostForm()
  if post.author != current_user:
    abort(403)
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash("Your post has been updated!", "success")
    return redirect(url_for("posts.post", post_id=post.id))

  elif request.method == "GET":
    form.title.data = post.title
    form.content.data = post.content


  return render_template("create_update_post.html", post=post, title=post.title, form=form, legend="Update Post")



@posts.route("/post/<int:post_id>/delete")
@login_required
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403)
  
  db.session.delete(post)
  db.session.commit()

  flash("Post Deleted!", "success")
  return redirect(url_for("main.home"))

screenblack/users/routes.py
import os
from flask import url_for, render_template, flash, request, redirect, Blueprint, current_app
from flask_login import current_user, login_user, logout_user, login_required
from screenblack import db, bcrypt
from screenblack.models import User, Post
from screenblack.users.forms import RegistrationForm, LoginForm, UpdateAccountForm

from screenblack.users.utils import save_picture

users = Blueprint("users", __name__)   

@users.route("/register", methods=["GET", "POST"])
def register():
  if current_user.is_authenticated:
    return redirect(url_for("main.home"))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
    user = User(name = form.name.data, username = form.username.data, email = form.email.data, password = hashed_password)
    db.session.add(user)
    db.session.commit()
    flash(f"Account created!", "success")
    return redirect(url_for("users.login"))
  return render_template("register.html", title = "Sign Up", form = form)


@users.route("/login", methods=["GET", "POST"])
def login():
  if current_user.is_authenticated:
    return redirect(url_for("main.home"))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email = form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get("next")
      return redirect(next_page) if next_page else redirect(url_for("main.home"))
    else:
      flash("Login Unsuccessful", "danger")
  return render_template("login.html", title = "Login", form = form)

@users.route("/logout")
def logout():
  logout_user()
  return redirect(url_for("main.home"))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

  form = UpdateAccountForm()

  if form.validate_on_submit():

    if form.picture.data:
      old_pic = current_user.picture
      pic_file_name = save_picture(form.picture.data)
      current_user.picture = pic_file_name
      if old_pic != 'default.jpg':
        try:
          os.remove(os.path.join(current_app.root_path, 'static/profilepics', old_pic))
        except:
          pass
    
    current_user.name = form.name.data
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash("Your details have been Updated!", "success")
    return redirect(url_for("users.account"))
  elif request.method =="GET":
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.email.data = current_user.email

  picture = url_for('static', filename='profilepics/' + current_user.picture)
  return render_template('account.html', title='Account', picture=picture, form=form)

@users.route("/user/<string:username>")
def user_about(username):
  page = request.args.get("page", default=1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page = page, per_page=5)
  return render_template("user_about.html", user = user, posts = posts, title = username)

screenblack/templates/about.html
{% extends "layout.html" %}
{% block content %}

<h1>About Developer</h1>
<small>Not About the app, Cause this is my app.</small>

<div class="about">
  <p>I’m Nihar – a thinker, learner etc. etc.</p>

  <p>
    I am pursuing my Btech in Nit Rourkela. Where I developed my love for thinking. I thought Linux would be sexy, I dual-booted my machine, and all worked fine, deleted the healthy recovery partition, and everything went down the drain.
  </p>

  <p>
    In my free time, I think about contributing to open-source projects. And when you start thinking about something, you think of thinking more about the thing, then you start thinking more & more of the thought you're thinking of, of thinking of the thing. And now you must be thinking about what I just wrote about thinking of, thinking of the thing ...of what&quest;&quest;&quest;
  </p>

  <p>
    When I’m not programming, I listen to music, watch football, and I imagine myself exercise.
  </p>
</div>

<a href="https://github.com/niharme/" target="_blank">Github</a>

{% endblock content %}

screenblack/templates/account.html
{% extends "layout.html" %} {% block content %}

<div class="dashboard">
  <h1 class="page-heading">Dashboard</h1>
  <div class="profile-card">

    <!-- <img src="https://avatars.dicebear.com/api/identicon/{{current_user.username}}.svg" alt="profile picture for {{ current_user.username }}" class="profile-image"> -->
    

    <img src="{{ picture }}" alt="profile picture for {{ current_user.name }}" class="profile-image">
  
    <h2 class="profile-card-name">{{ current_user.name }}</h2>
    <h2 class="profile-card-username">@{{ current_user.username }}</h2>
    <p class="profile-card-email">{{ current_user.email }}</p>
  </div>
  

  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset>
      <div class="form-fields">
        <div class="form-field">
          {{ form.name.label(class='label') }}
          {% if form.name.errors %}
            {{ form.name(class="input-field") }}
  
            <div class="invalid-feedback">
              {% for error in form.name.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.name(class="input-field") }}
          {% endif %}
        </div>

        <div class="form-field">
          {{ form.username.label(class='label') }}
          {% if form.username.errors %}
            {{ form.username(class="input-field") }}
  
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="input-field") }}
          {% endif %}
        </div>
  
        <div class="form-field">
          {{ form.email.label(class='label') }}
          {% if form.email.errors %}
            {{ form.email(class="input-field") }}
  
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="input-field") }}
          {% endif %}
        </div>
        <div class="form-field">
          {{ form.picture.label(class="custom-file-upload") }}
          {{ form.picture() }}
          {% if form.picture.errors %}
            {% for error in form.picture.errors %}
              <span class="text-danger">{{ error }}</span>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      
    </fieldset>
    <div class="form-fields">{{ form.submit(class="submit-btn btn") }}</div>
  </form>


</div>

{% endblock content %}

screenblack/templates/create_update_post.html
{% extends "layout.html" %}
{% block content %}

  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset>
      <legend>{{ legend }}</legend>
      <div class="form-fields">
        <div class="form-field">
          {{ form.title.label(class='label') }}
          {% if form.title.errors %}
            {{ form.title(class="input-field") }}

            <div class="invalid-feedback">
            {% for error in form.title.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.title(class="input-field") }}
          {% endif %}
        </div>

        <div class="form-field">
          {{ form.content.label(class='label') }}
          {% if form.content.errors %}
            {{ form.content(class="content-input-field") }}

            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.content(class="content-input-field") }}
          {% endif %}
        </div>

      </div>

      <div class="form-fields">{{ form.submit(class="submit-btn btn") }}</div>
      
    </fieldset>
  </form>

{% endblock content %}

screenblack/templates/home.html
{% extends "layout.html" %}
{% block content %}
  {% for post in posts.items %}

    <article class="article-body">
      <div class="home-article">
        <div class="article-author-picture">
          <a href="{{ url_for('users.user_about', username=post.author.username) }}"><img class="profilepic-mini" src="{{ url_for('static', filename='profilepics/'+post.author.picture) }}" alt="profile picture for {{ post.author.name }}"></a>
        </div>
        <div class="article-author-details">
          <a class="article-author" href="{{ url_for('users.user_about', username=post.author.username) }}">{{ post.author.name }}</a>
          <small class="text-muted">on</small>
          <small class="article-date">{{ post.date_posted.strftime("%B %d, %Y") }}</small>
        </div>
      </div>
      <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <div class="article-content">
        <p>{{ post.content }}</p>
      </div>
    </article>

  {% endfor %}

  <div class="pagination">
    {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
      {% if page_num %}
        {% if page_num == posts.page %}
          <a class="link-current" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

{% endblock content %}

screenblack/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% if title %}
    <title>Screen Black | {{title}}</title>
    {% else %}
    <title>Screen Black | Home</title>
    {% endif %}

    <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}" />

    <link rel="shortcut icon" href="{{ url_for('static', filename='icons/favicon.ico') }}" type="image/x-icon">

  </head>
  <body>
    <div class="container">
      <!-- header section -->
      <header class="site-header">
        <!-- header logo and brand name -->
        <div class="header-top">
          <div class="header-logo">
            <a href="/">
              <div class="logo">Screen Black</div>
            </a>
          </div>
        </div>

        <!-- navigation menu -->
        <nav class="menu">
          <ul class="left-menu">
            <li><a href="{{url_for('main.home')}}">Home</a></li>
            <li><a href="{{url_for('main.about')}}"><del>About</del></a></li>
          </ul>
          <ul class="right-menu">
          {% if current_user.is_authenticated %}
            <li><a href="{{url_for('posts.create_post')}}">Create Post</a></li>
            <li><a href="{{url_for('users.account')}}">Account</a></li>
            <li><a href="{{url_for('users.logout')}}">Logout</a></li>
          {% else %}
            <li><a href="{{url_for('users.login')}}">Login</a></li>
            <li><a href="{{url_for('users.register')}}">Sign Up</a></li>
          {% endif %}
          </ul>
        </nav>
      </header>
      <main class="content">
        <div class="framed-content">
          {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %} {% endblock content %}
        </div>
      </main>
    </div>
  </body>
</html>

screenblack/templates/login.html
{% extends "layout.html" %} {% block content %}

<form method="POST" action="">
  {{ form.hidden_tag() }}
  <fieldset>
    <legend>Login</legend>
    <div class="form-fields">
      <div class="form-field">
        {{ form.email.label(class='label') }}
        {% if form.email.errors %}
          {{ form.email(class="input-field") }}

            <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
        {% else %}
          {{ form.email(class="input-field") }}
        {% endif %}
      </div>

      <div class="form-field">
        {{ form.password.label(class='label') }}
        {% if form.password.errors %}
          {{ form.password(class="input-field") }}

          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="input-field") }}
        {% endif %}
      </div>
      <div class="form-field bool-field">
        {{ form.remember.label(class='label') }}
        {{ form.remember(class="bool-input-field") }}
      </div>
    </div>
    <div class="form-fields">{{ form.submit(class="submit-btn btn") }}</div>
  </fieldset>
</form>

{% endblock content %}

screenblack/templates/new_post.html
{% extends "layout.html" %}
{% block content %}

  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset>
      <legend>New Post</legend>
      <div class="form-fields">
        <div class="form-field">
          {{ form.title.label(class='label') }}
          {% if form.title.errors %}
            {{ form.title(class="input-field") }}

            <div class="invalid-feedback">
            {% for error in form.title.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.title(class="input-field") }}
          {% endif %}
        </div>

        <div class="form-field">
          {{ form.content.label(class='label') }}
          {% if form.content.errors %}
            {{ form.content(class="input-field") }}

            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.content(class="input-field") }}
          {% endif %}
        </div>

      </div>

      <div class="form-fields">{{ form.submit(class="submit-btn btn") }}</div>
      
    </fieldset>
  </form>

{% endblock content %}

screenblack/templates/post.html
{% extends "layout.html" %}
{% block content %}

  <article class="article-body">
    <div class="article-metadata">
      <div class="article-header">
        <div class="article-author-picture">
          <a href="{{ url_for('users.user_about', username=post.author.username) }}"><img class="profilepic-mini" src="{{ url_for('static', filename='profilepics/'+post.author.picture) }}" alt="profile picture for {{ post.author.name }}"></a>
        </div>
        <div class="article-author-details">
          <a class="article-author" href="{{ url_for('users.user_about', username=post.author.username) }}">{{ post.author.name }}</a>
          <small class="text-muted">on</small>
          <small class="article-date">{{ post.date_posted.strftime("%B %d, %Y") }}</small>
        </div>
      </div>
      {% if post.author == current_user %}
      <div class="article-modify">
        <a href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
        <a href="{{ url_for('posts.delete_post', post_id = post.id) }}">Delete</a>
      </div>
      {% endif %}
      
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <div class="article-content">
      <p>{{ post.content }}</p>
    </div>
  </article>

{% endblock content %}

screenblack/templates/register.html
{% extends "layout.html" %} {% block content %}

<form method="POST" action="">
  {{ form.hidden_tag() }}
  <fieldset>
    <legend>Join today</legend>
    <div class="form-fields">

      <div class="form-field">
        {{ form.name.label(class='label') }}
        {% if form.name.errors %}
          {{ form.name(class="input-field") }}

          <div class="invalid-feedback">
          {% for error in form.name.errors %}
            <span>{{ error }}</span>
          {% endfor %}
          </div>
        {% else %}
          {{ form.name(class="input-field") }}
        {% endif %}
      </div>

      <div class="form-field">
        {{ form.username.label(class='label') }}
        {% if form.username.errors %}
          {{ form.username(class="input-field") }}

          <div class="invalid-feedback">
          {% for error in form.username.errors %}
            <span>{{ error }}</span>
          {% endfor %}
          </div>
        {% else %}
          {{ form.username(class="input-field") }}
        {% endif %}
      </div>

      <div class="form-field">
        {{ form.email.label(class='label') }}
        {% if form.email.errors %}
          {{ form.email(class="input-field") }}

          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.email(class="input-field") }}
        {% endif %}
      </div>

      <div class="form-field">
        {{ form.password.label(class='label') }}
        {% if form.password.errors %}
          {{ form.password(class="input-field") }}

          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="input-field") }}
        {% endif %}
      </div>

      <div class="form-field">
        {{ form.confirm_password.label(class='label') }}
        {% if form.confirm_password.errors %}
          {{ form.confirm_password(class="input-field") }}

          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.confirm_password(class="input-field") }}
        {% endif %}
      </div>
    </div>

    <div class="form-fields">{{ form.submit(class="submit-btn btn") }}</div>
    <div class="form-fields">
      <small>Already have an account? <a href="{{url_for('users.login')}}">Login</a> now.</small>
    </div>
  </fieldset>
</form>

{% endblock content %}

screenblack/templates/user_about.html
{% extends "layout.html" %}
{% block content %}


  <div class="profile-card">
    <img src="{{ url_for('static', filename='profilepics/'+user.picture) }}" alt="profile picture for {{ user.name }}" class="profile-image">

    <h2 class="profile-card-name">{{ user.name }}</h2>
    <h3 class="profile-card-username">@{{ user.username }}</h2>
  </div>

  <h1 class="user-about-heading">Posts{{ user.posts.total }}</h1>

  {% for post in posts.items %}

    <article class="article-body">
      <div class="home-article">
        <div class="article-author-details">
          <a class="article-author">{{ post.author.name }}</a>
          <small class="text-muted">on</small>
          <small class="article-date">{{ post.date_posted.strftime("%B %d, %Y") }}</small>
        </div>
      </div>
      <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <div class="article-content">
        <p>{{ post.content }}</p>
      </div>
    </article>

  {% endfor %}

  <div class="pagination">
    {% for page_num in posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
      {% if page_num %}
        {% if page_num == posts.page %}
          <a class="link-current" href="{{ url_for('users.user_about', username = user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a href="{{ url_for('users.user_about', username = user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

{% endblock content %}